# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2

  # Datasource
  datasource:
    url: jdbc:h2:file:./data/app_db;DB_CLOSE_ON_EXIT=FALSE
    username: stockman
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  quartz:
    job-store-type: memory
    jdbc:
      initialize-schema: never
